"""Add CVSS scoring and enhanced vulnerability tracking

Revision ID: 2b2df591b1c4
Revises: 9517b21b3da6
Create Date: 2025-11-26 11:03:45.233586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2df591b1c4'
down_revision = '9517b21b3da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cvss_vector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('references', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vulnerabilities_cve_id'), ['cve_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_severity'), ['severity'], unique=False)

    with op.batch_alter_table('vulnerability_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('protocol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('service', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('false_positive_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fixed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vulnerability_instances_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_instances_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_instances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_instances_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_instances_vulnerability_id'), ['vulnerability_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_instances_vulnerability_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_instances_target_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_instances_status'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_instances_scan_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_instances_detected_at'))
        batch_op.drop_column('verified_at')
        batch_op.drop_column('fixed_at')
        batch_op.drop_column('false_positive_reason')
        batch_op.drop_column('evidence')
        batch_op.drop_column('service')
        batch_op.drop_column('protocol')
        batch_op.drop_column('port')

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_severity'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_name'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_cve_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('references')
        batch_op.drop_column('category')
        batch_op.drop_column('cvss_vector')
        batch_op.drop_column('cvss_score')

    # ### end Alembic commands ###
