"""Add progress tracking and OpenVAS fields to Scan model

Revision ID: 3e573d3fbe4b
Revises: 26b654f2108d
Create Date: 2025-11-24 16:36:31.414943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e573d3fbe4b'
down_revision = '26b654f2108d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('eta_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('openvas_task_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('openvas_report_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('openvas_report_id')
        batch_op.drop_column('openvas_task_id')
        batch_op.drop_column('eta_seconds')
        batch_op.drop_column('current_step')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
