"""Add creator_id to teams

Revision ID: 4742175c5fc9
Revises: 10045d349f90
Create Date: 2025-12-13 09:03:12.563452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4742175c5fc9'
down_revision = '10045d349f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_teams_creator_id_users', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_creator_id_users', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
