"""Add performance indexes

Revision ID: 650c533e1290
Revises: 4742175c5fc9
Create Date: 2025-12-13 09:48:59.766705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650c533e1290'
down_revision = '4742175c5fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_ip_address'), ['ip_address'], unique=False)

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_created_at'))

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_ip_address'))
        batch_op.drop_index(batch_op.f('ix_targets_created_at'))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_status'))
        batch_op.drop_index(batch_op.f('ix_scans_started_at'))

    # ### end Alembic commands ###
