"""Sync schema

Revision ID: 804d9591ab48
Revises: 75fde4930e20
Create Date: 2025-12-09 17:58:28.261034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804d9591ab48'
down_revision = '75fde4930e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('dashboard_configs',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=True),
    # sa.Column('is_default', sa.Boolean(), nullable=True),
    # sa.Column('team_id', sa.Integer(), nullable=True),
    # sa.Column('layout_data', sa.JSON(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('saved_searches',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=True),
    # sa.Column('query', sa.String(length=255), nullable=True),
    # sa.Column('filters', sa.JSON(), nullable=True),
    # sa.Column('is_history', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('comments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('text', sa.Text(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.Column('vulnerability_instance_id', sa.Integer(), nullable=True),
    # sa.Column('ticket_id', sa.Integer(), nullable=True),
    # sa.Column('parent_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    # sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.ForeignKeyConstraint(['vulnerability_instance_id'], ['vulnerability_instances.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_teams_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('uq_teams_name', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('role')

    op.drop_table('comments')
    op.drop_table('saved_searches')
    op.drop_table('dashboard_configs')
    # ### end Alembic commands ###
