"""Update Ticket model

Revision ID: 881f015be26d
Revises: 847486329c1f
Create Date: 2025-11-24 11:49:07.436775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881f015be26d'
down_revision = '847486329c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_vulnerabilities',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_instance_id'], ['vulnerability_instances.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'vulnerability_instance_id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_assignee_id_users', 'users', ['assignee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_assignee_id_users', type_='foreignkey')
        batch_op.drop_column('assignee_id')

    op.drop_table('ticket_vulnerabilities')
    # ### end Alembic commands ###
