"""add report columns to scans

Revision ID: b8f9c2d1e4a7
Revises: a4331a369d50
Create Date: 2025-11-27 08:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b8f9c2d1e4a7'
down_revision = 'a4331a369d50'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('report_pdf', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('report_pdf')
        batch_op.drop_column('report_html')
    # ### end Alembic commands ###
