"""Add OS fields to targets

Revision ID: f22b3f2c50c0
Revises: 534676a54562
Create Date: 2025-12-03 08:58:15.713357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22b3f2c50c0'
down_revision = '534676a54562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('os_cpe', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('os_last_detected', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_column('os_last_detected')
        batch_op.drop_column('os_cpe')
        batch_op.drop_column('os_name')
    # ### end Alembic commands ###
